---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grant-access-to-locust
  namespace: default
subjects:
- kind: ServiceAccount
  name: locust-master
  namespace: locust
- kind: ServiceAccount
  name: locust-worker
  namespace: locust
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
